services:
  - type: web
    name: wordle-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    root: ./backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com

  - type: static
    name: wordle-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    root: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com